ACO
Cortuzz/WeebAlgorithms pull request #32
Opened 2022-03-25 01:53 UTC by Cortuzz

Not done yet:
1. Pheromones rendering
2. Selecting a specific render
3. Some "danger" settings

2022-04-01 15:21 UTC, Ssslakter commented on src/js/ants/alg/ant.js
> +        if (this.moveTimer.tickAndCheck()) {
На самом деле tickAndCheck() не особо говорит о значении функции, особенно, когда я вижу условную конструкцию - непонятно когда по логике возвращется true или false. Можно назвать например isTimeToRotate или еще как-то.

2022-04-02 09:04 UTC, Ssslakter requested changes
Есть небольшие вопросы

2022-04-02 09:04 UTC, ssslakter commented on src/js/ants/alg/simulation.js
> +    }
Не совсем понятно что здесь происходит

2022-04-02 09:04 UTC, ssslakter commented on src/js/ants/alg/worker.js
> +    }
Вот вкупе с предыдущим комментом, хочу прояснить, как оно работает, на что влияет индекс колонии?
И, насколько я понял, `this.changeColony()` добавляет муравья в список муравьев колонии, но что если он уже был в этой колонии?🤔

2022-04-02 09:04 UTC, ssslakter commented on src/js/ants/alg/ant.js
> +        this.visionAngleStep = step * this.visionAngle;
Думаю логичней было бы сделать `step `целым и поделить `this.visionAngle` на `step`, так читаться легче будет, ну это так по мелочи

2022-04-02 09:04 UTC, ssslakter commented on src/js/ants/alg/simulation.js
> +    }
А именно, почему вычитается индекс?

2022-04-02 09:04 UTC, ssslakter commented on src/js/ants/alg/worker.js
> +                    }
вот тоже непон, но наверное я спать хочу, завтра еще поразбираюсь, но если несложно, то можешь пояснить
Не понял я именно почему мы перезаписываем `bestAngles `

2022-04-02 09:04 UTC, ssslakter commented on src/js/ants/canvas_setup.js
> +}
харам _(нет новой строки **(пофиг)**)_

2022-04-02 09:04 UTC, ssslakter commented on src/js/ants/alg/fighter.js
> +                   }
Почему он бьет других муравьев, хотя сам не в этой клетке

2022-04-02 09:04 UTC, ssslakter commented on src/js/ants/alg/colony.js
> +            }
в чем смысл этого действия если хп муравья больше 0

2022-04-02 09:04 UTC, ssslakter commented on src/js/ants/alg/simulation.js
> +        }
возможно вот это довольно много по трудоемкости занимает

2022-04-02 09:04 UTC, Ssslakter commented on src/js/ants/handler.js
> +async function antsAlg(simulation, colony) {
Что на входе делает `simulation`?

2022-04-02 11:28 UTC, Cortuzz commented on src/js/ants/alg/fighter.js
> +                   }
потому что он просматривает пространство вокруг себя, если бы он бил только в одну клетку то это не имело бы никакого значения, шанс этого очень мал

2022-04-02 11:30 UTC, Cortuzz commented on src/js/ants/alg/colony.js
> +            }
муравей может погибнуть (69 строчка colony.js) по двум причинам: долгая автономия и убийство другим муравьем, если случился кейс долгой автономности, то нужно заменить муравья новым, в противном случае этого делать не надо (теряется смысл файтеров).

2022-04-02 11:39 UTC, Cortuzz commented on src/js/ants/alg/simulation.js
> +    }
потому что на матрице тип клетки задается не объектами а числами, а так как колоний может быть больше одной, соответственно, числа должны быть разными: константа колонии (-3) минус её индекс.

2022-04-02 11:40 UTC, Cortuzz commented on src/js/ants/alg/worker.js
> +    }
Нет, данный метод заставляет муравья вновь искать еду (если он её дошел до коллизии с колонией)

2022-04-02 11:42 UTC, Cortuzz commented on src/js/ants/alg/worker.js
> +                    }
Если муравей видит равнозначные по феромонам углы - записывает их в массив лучших углов (а затем выберет из них среднее), если же муравей нашел угол лучше - удаляет все предыдущие углы.

2022-04-02 11:46 UTC, Cortuzz commented on src/js/ants/alg/ant.js
> +        if (this.moveTimer.tickAndCheck()) {
moveTimer - объект класса Cooldown (он, в свою очередь, явно не должен иметь метода isTimeToRotate). Метод класса Cooldown tickAndCheck() имхо интуитивно понятен.

2022-04-02 11:52 UTC, Cortuzz commented on src/js/ants/alg/ant.js
> +        this.visionAngleStep = step * this.visionAngle;
Так изначально и было, однако, я наоборот подумал, что читаемость будет лучше (мол ставишь 0.1, значит смотрит по 0.1 (короче хз))

2022-04-02 11:55 UTC, Cortuzz commented on src/js/ants/handler.js
> +async function antsAlg(simulation, colony) {
Fixed

2022-04-02 11:55 UTC, Cortuzz commented on src/js/ants/canvas_setup.js
> +}
Fixed

2022-04-02 12:01 UTC, Ssslakter commented on src/js/ants/alg/simulation.js
> +    }
Так разве сначала не сравнение выполняется, а потом вычитание?

2022-04-02 12:04 UTC, Cortuzz commented on src/js/ants/alg/simulation.js
> +    }
![Screenshot from 2022-04-02 19-03-50](https://user-images.githubusercontent.com/52497929/161382260-8a0d3592-7408-404c-9c60-4506df14706a.png)

2022-04-02 12:05 UTC, Ssslakter commented on src/js/ants/alg/worker.js
> +    }
А где он удаляется? 
Я прошелся по все функциям внутри, там по итогу колония  `addAnt(AntType)` вызывает и создает нового муравья

2022-04-02 12:14 UTC, Ssslakter approved these changes

2022-04-02 12:15 UTC, merged