Path-finder algorithm basic
Cortuzz/WeebAlgorithms pull request #7
Opened 2022-03-04 14:33 UTC by Ssslakter

Пока просто создам реквест, думаю пулить все равно будем после полной реализации.
А ну и почекайте код, может чего упростить надо

2022-03-04 14:45 UTC, Cortuzz commented on src/js/path_finder/finder.js
> +function Find(x, y, array) {
wrong code style

2022-03-04 15:09 UTC, Cortuzz requested changes
Code style review:

1. wrong code style
2. bad script link into html file
3. _bad variables naming (maybe)_

Tech review:

1. function returns -1 instead exception
**Tech review is incomplete**

2022-03-04 15:09 UTC, Cortuzz commented on src/js/path_finder/finder.js
> +function EuclidHeuristic(pointA, pointB) {
wrong code style (functions only in lowerCamelStyle)

2022-03-04 15:09 UTC, Cortuzz commented on src/js/path_finder/finder.js
> +function ManhattanHeuristic(pointA, pointB) {
wrong code style (functions only in lowerCamelStyle)

2022-03-04 15:09 UTC, Cortuzz commented on src/js/path_finder/finder.js
> +function Find(x, y, array) {
wrong code style (functions only in lowerCamelStyle)

2022-03-04 15:09 UTC, Cortuzz commented on src/js/path_finder/finder.js
> +class point {
wrong code style (classes only in CamelStyle)

2022-03-04 15:09 UTC, Cortuzz commented on src/js/path_finder/finder.js
> +    return -1;
Лучше кинуть исключение в данном случае

2022-03-04 15:09 UTC, Cortuzz commented on src/js/path_finder/finder.js
> +    FindPath(start, finish) {
wrong code style (methods only in lowerCamelStyle)

2022-03-04 15:09 UTC, Cortuzz commented on src/templates/path_finder.html
> +    <script src="../js/path_finder/finder.js"></script>
Не требуется, файл алгоритма должен взаимодействовать со страницей через посредника (файл hander.js)

2022-03-04 15:09 UTC, Cortuzz commented on src/js/path_finder/finder.js
> +        this.h = Number.MAX_VALUE;
Не совсем понятно для чего переменные (если они исполняют какую-то важную роль), лучше их переименовать в более понятные

2022-03-04 17:41 UTC, Ssslakter commented on src/templates/path_finder.html
> +    <script src="../js/path_finder/finder.js"></script>
Ну я тестировать то как то должен был...

2022-03-04 17:42 UTC, Ssslakter commented on src/js/path_finder/finder.js
> +        this.h = Number.MAX_VALUE;
Что конкретно непонятно

2022-03-04 17:43 UTC, Ssslakter commented
Че за душный ревью, ваще ниче не по фактам. Нафиг мне исключение выкидывать в нормальной функции которая просто не нашла элемент😠

2022-03-04 17:45 UTC, Cortuzz commented on src/templates/path_finder.html
> +    <script src="../js/path_finder/finder.js"></script>
окей, но на будущее просто - в прод явно нежелательно такое отправлять

2022-03-04 17:50 UTC, Cortuzz commented
В данной ситуации (и с данным языком) проблем будет не так много, как, например, при работе с объектами. Самое страшное происходит в строго типизированном языке когда твоя функция ищет какие-то объекты класса, в этом случае единственный вариант вернуть что-то из функции помимо объекта - null, а за null из функции бьют очень сильно. Поэтому лучше сразу принять на вооружение тот факт, что выкидывать при отсутствии решения, нахождения чего-то, etc. лучше все исключение, которое, в случае чего, будет уже обработано. (Но на самом деле да - в данной ситуации это не критично, однако с объектами было бы все хуже).

2022-03-04 17:50 UTC, Cortuzz commented on src/js/path_finder/finder.js
> +        this.h = Number.MAX_VALUE;
this.h
this.g

2022-03-05 15:37 UTC, Ssslakter commented on src/js/path_finder/finder.js
> +        this.h = Number.MAX_VALUE;
Название функции h и g, дефолтные названия для алгоритма

2022-03-05 17:12 UTC, Cortuzz approved these changes
Ok.
Variable names need to be changed (did it myself)

2022-03-05 17:13 UTC, merged